### ISSUE TITLE
Program Stops at Image Analysis

### ISSUE THREAD

**Issue by yapursss** [JotaRata/StarTrak#6]
While the program analyzes the image, this appears in the terminal: 

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/mnt/c/Users/BenjaminYapur/Desktop/StarTrak-master/STCore/ImageView.py", line 191, in <lambda>
    cmdTrack = lambda : Apply(root, items)
  File "/mnt/c/Users/BenjaminYapur/Desktop/StarTrak-master/STCore/ImageView.py", line 279, in Apply
    Tracker.Awake(root, Stars, items)
  File "/mnt/c/Users/BenjaminYapur/Desktop/StarTrak-master/STCore/Tracker.py", line 74, in Awake
    CreateCanvas(ItemList,stars)
  File "/mnt/c/Users/BenjaminYapur/Desktop/StarTrak-master/STCore/Tracker.py", line 299, in CreateCanvas
    UpdateCanvasOverlay(stars, CurrentFile, BrightestStar)
  File "/mnt/c/Users/BenjaminYapur/Desktop/StarTrak-master/STCore/Tracker.py", line 414, in UpdateCanvasOverlay
    trackPos = (TrackedStars[stIndex].currPos[1], TrackedStars[stIndex].currPos[0])
IndexError: list index out of range

**Comment by JotaRata** [comment]
Tested and Fixed in d83f949
